const AUTH_TYPES = {
    AUTH_LOGIN:'AUTH_LOGIN',
    AUTH_LOGOUT:'AUTH_LOGOUT'
};

const MONEYBOX_TYPES = {
    INCREMENT_COINS:'INCREMENT_COINS',
    DECREMENT_COINS:'DECREMENT_COINS',
    INCREMENT_NEW_COINS:'INCREMENT_NEW_COINS',
    DECREMENT_NEW_COINS:'DECREMENT_NEW_COINS',
    INCREMENT_MINIONS:'INCREMENT_MINIONS',
    DECREMENT_MINIONS:'DECREMENT_MINIONS',
};

export const ACTION_TYPES = {
    AUTH_TYPES,
    MONEYBOX_TYPES
};
