const ORIENTATION_TYPES = {
    CHANGE_ORIENTATION:'CHANGE_ORIENTATION',
};

const AUTH_TYPES = {
    AUTH_LOGIN:'AUTH_LOGIN',
    AUTH_LOGOUT:'AUTH_LOGOUT',
};

const MONEYBOX_TYPES = {
    INCREMENT_COINS:'INCREMENT_COINS',
    DECREMENT_COINS:'DECREMENT_COINS',
    INCREMENT_NEW_COINS:'INCREMENT_NEW_COINS',
    DECREMENT_NEW_COINS:'DECREMENT_NEW_COINS',
    INCREMENT_MINIONS:'INCREMENT_MINIONS',
    DECREMENT_MINIONS:'DECREMENT_MINIONS',
};

const MINIONS_TYPES = {
    UNLOCK_MINION:'UNLOCK_MINION',
    BLOCK_MINION:'BLOCK_MINION',
};

export const ACTION_TYPES = {
    ORIENTATION_TYPES,
    AUTH_TYPES,
    MONEYBOX_TYPES,
    MINIONS_TYPES
};
